### ISSUE TITLE
Delete log missing @

### ISSUE THREAD

**Issue by esatterwhite** [instructure/jsoncdc#4]
### Description ###

I'm experimenting with logical replication with this decoding plugin. 
I just inserted a bunch of dummy records into a table in a single transaction, then try to delete one of them by id.
It's mostly just fine, but deletes tend to be missing the tuple information that was deleted

it will just have 
```javascript
{ delete: {}, table: '<table name>' }
```

and will be missing the `@` property.

### Additional Information ###
`rustc` : 1.26.2
platform alpine linux

**Comment by Mythra** [comment]
Hey @esatterwhite Thanks for reporting this, Which version of postgres are you using?

**Comment by esatterwhite** [comment]
PostgreSQL 10.5

**Comment by Mythra** [comment]
Hey @esatterwhite ,

I'm not seeing this with my testing table. However digging into this a bit more. This would be expected behavior if your table does ***not*** have a primary key.

**Comment by esatterwhite** [comment]
ah. yep. I think you're right. will confirm in a little bit

**Comment by esatterwhite** [comment]
Yep. User Error!
Thanks.
